site_name: 'teste lucas'
site_description: 'Local para documentacao'
repo_url: https://github.com/FaveroLucas/arquivos-backstage-lucas

plugins:
  - techdocs-core

nav:
  - FAQ:
    - Index: 'index.md'
