apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ms_integracao_produto
  description: Microservico que realiza a integracao de produto na solus
spec:
  type: openapi
  lifecycle: production
  owner: builders
  system: mit
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: ms-integracao-produto
      license:
        name: MIT
    servers:
      - url: https://bitbucket.org/platformbuilders/ms-integracao-produto-solus-maringa/src/desenvolvimento/?search_id=043e47cf-0aba-4d6c-a02b-80cfafd2aae2