apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: teste-gleison-api
  description: teste-yaml-gleison-api
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: examples
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
