apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: mit
  description: Integração de fornecedores
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: builders
  domain: CSC